### PR TITLE
add test-file to test blas/numpy compatibility

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by looooo** [comment]
Ah, this makes sense, but I think liblapack was pulled anyway (maybe as seconsary dependency).

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
